#!/usr/bin/env sh

loglog="log.log"

main() {
    base="$HOME/data/instagram"

    num=$(( "$( find "$base/.." -mindepth 1 -maxdepth 1 -type d -name "log*" -printf "%f\n" | sort -V | tail -n 1 | sed 's/log//' )" + 1 ))

    mkdir "$base/../log$num" || return 1
    cp "$base/$loglog" "$base"/usr_*.log "$base/../log$num" || return 1

    grep -E ':\sOK' "$base"/usr_*.log | awk '{print $2}' | sed -e 's/\:$//' -e 's/.*\///' >> "$base/$loglog"
    sort "$base/$loglog" -o "$base/$loglog"
}

main || echo "Logging failed on $( date )."
