#!/usr/bin/env bash

base="$HOME/data/ig"
loglog="log.log"
tmplog="tmp.log"
chunk=200

main()
{
    cd "$base" || return 1

    dirs="$( find . -mindepth 1 -maxdepth 1 -type d | sed 's/^\.\///' | sort )"

    echo "$dirs" | while read -r i
    do
        files="$( find "$i" -mindepth 1 -maxdepth 1 -regextype grep -type f -iregex "^.*[jpg|mp4]" -and -not -iregex "^.*\.part$" -printf "%f\n" | sort )"
        filesList=()

        while read -r j
        do
            grep -Fxq "$j" "$loglog" || filesList+=( "$i/$j" )
        done < <(echo "$files")

        if [ "$filesList" ]
        then
            len="${#filesList[@]}"
            k=1
            while [ "$k" -le "$len" ]
            do
                filesRange=()
                for (( l = k; l < k + chunk; l++ ))
                do
                    [ "$l" -gt "$len" ] && break
                    filesRange+=( "${filesList[$l]}" )
                done

                touch "$tmplog"
                gpup -a "$i" "${filesRange[@]}" | tee "$tmplog"
                cat "$tmplog" >> "usr_$i.log"

                (( k+=chunk ))

                echo "[GPUPUP]: Safe to cancel. (#$k)"
            done

            return 0
        fi
   done

   rm "$tmplog"
}

main || echo "[GPUPUP]: Error on $( date )."
