#!/usr/bin/env sh

loglog="log.log"
base="$HOME/data/ig"

main() {
    num=$(( "$( find "$base/../ig-log" -mindepth 1 -maxdepth 1 -type d -printf "%f\n" | sort -V | tail -n 1 )" + 1 ))

    mkdir "$base/../ig-log/$num" || return 1
    cp "$base/$loglog" "$base"/usr_*.log "$base/../ig-log/$num" || return 1

    grep -E ':\sOK' "$base"/usr_*.log | awk '{print $2}' | sed -e 's/\:$//' -e 's/.*\///' >> "$base/$loglog"
    sort "$base/$loglog" -o "$base/$loglog"
    rm "$base"/usr_*.log
}

main || echo "Logging failed on $( date )."
