#!/usr/bin/env bash

base="$HOME/data/ig"
tmplog="tmp.log"
loglog="log.log"

main()
{
    cd "$base" || return 1

    dirs="$( find . -mindepth 1 -maxdepth 1 -type d | sed 's/^\.\///' | sort )"

    echo "$dirs" | while read -r i
    do
        files="$( find "$i" -mindepth 1 -maxdepth 1 -regextype grep -type f -iregex "^.*[jpg|mp4]" -and -not -iregex "^.*\.part$" -printf "%f\n" | sort )"
        filesList=()

        while read -r j
        do
            grep -Fxq "$j" "$loglog" || filesList+=( "$i/$j" )
        done < <(echo "$files")

        if [ "$filesList" ]
        then
            touch "$tmplog"
            gpup -a "$i" "${filesList[@]}" | tee "$tmplog"
            cat "$tmplog" >> "usr_$i.log"
        fi
   done

   rm "$tmplog"
}

main || echo "[GPUPUP]: Error on $( date )."
